### ISSUE TITLE
Modification application to refine the rating oscillator for W rotations

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/crypto-screener#9]
Objective: Improve recognition of bullish and bearish local trend in W rotation

Steps:
[] Modifying the base_screening table
         - rsi_14 -> rsi_14_D
         - oscillators_rating -> oscillators_rating_D
[] Add columns to the base_screening table
         - rsi_14_4h (add calculation in application)
         - oscillators_rating_4h (add calculation in application)
[] Editing sql for searching 4h imbalance and D imbalance

Branch: feature/improve_oscillators_rating_for_W_consolidation -> DEV

**Comment by LucyQuantAnalyst** [comment]
added to aplication in commmit  [aeda16c](https://github.com/GeorgeQuantAnalyst/crypto-screener/commit/aeda16cfa3f004324b3e3d8fbef54ce124d81029)
